apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fycxmb5ya-python 
  janus-idp.io/tekton: fycxmb5ya-python
  backstage.io/kubernetes-id: fycxmb5ya-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fycxmb5ya-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml