apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fycxmb5ya-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fycxmb5ya-python 
  name: fycxmb5ya-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: fycxmb5ya-python 
